name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install ci
      run: npm ci
    - name: test
      run: ng test
    - name: build
      run: ng build -c production
